# Generated by Django 4.0 on 2021-12-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_empapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_no',
            field=models.AutoField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
