# Generated by Django 4.0 on 2021-12-14 10:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm_empapp', '0003_rename_user_users_alter_employee_emp_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_no',
            field=models.CharField(default=uuid.uuid4, max_length=50),
        ),
    ]
