# Generated by Django 4.0 on 2021-12-14 10:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm_empapp', '0004_alter_employee_emp_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUUIDModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm_empapp.myuuidmodel'),
        ),
    ]
