# Generated by Django 4.0 on 2021-12-14 11:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm_empapp', '0005_myuuidmodel_alter_employee_emp_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_no',
            field=models.CharField(default=uuid.uuid4, max_length=50),
        ),
        migrations.DeleteModel(
            name='MyUUIDModel',
        ),
    ]
