# Generated by Django 4.0 on 2021-12-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_empapp', '0006_alter_employee_emp_no_delete_myuuidmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_no',
            field=models.CharField(max_length=50),
        ),
    ]
